version: '3.7'

services:
  mongo_db:
    container_name: adminjs-example-mongo
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  postgres_db:
    container_name: adminjs-example-postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=adminjs
      - POSTGRES_USER=adminjs
      - POSTGRES_PASSWORD=adminjs
    ports:
      - "5435:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  mysql_db:
    container_name: adminjs-example-mysql
    platform: linux/x86_64
    image: mysql
    environment:
      MYSQL_USER: adminjs
      MYSQL_PASSWORD: adminjs
      MYSQL_ROOT_PASSWORD: adminjs
      MYSQL_DATABASE: adminjs
    ports:
      - "3308:3306"
    volumes:
      - mysql_db:/var/lib/mysql

volumes:
  mongo_db:
  postgres_db:
  mysql_db:
