version: '3.7'

services:
  mongo:
    container_name: adminjs-example-mongo
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  postgres-for-sequelize:
    container_name: adminjs-example-postgres-for-sequelize
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=adminjs
      - POSTGRES_USER=adminjs
      - POSTGRES_PASSWORD=adminjs
    ports:
      - "5435:5432"
    volumes:
      - postgres_for_sequelize_db:/var/lib/postgresql/data

  postgres-for-typeorm:
    container_name: adminjs-example-postgres-for-typeorm
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=adminjs-typeorm
      - POSTGRES_USER=adminjs
      - POSTGRES_PASSWORD=adminjs
    ports:
      - "5436:5432"
    volumes:
      - postgres_for_typeorm_db:/var/lib/postgresql/data

  postgres-for-mikroorm:
    container_name: adminjs-example-postgres-for-mikroorm
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=adminjs-mikroorm
      - POSTGRES_USER=adminjs
      - POSTGRES_PASSWORD=adminjs
    ports:
      - "5437:5432"
    volumes:
      - postgres_for_mikroorm_db:/var/lib/postgresql/data

  mysql-for-prisma:
    container_name: adminjs-example-mysql-for-prisma
    platform: linux/x86_64
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: adminjs
      MYSQL_DATABASE: adminjs
    ports:
      - "3308:3306"
    volumes:
      - mysql_for_prisma:/var/lib/mysql

volumes:
  mongo_db:
  postgres_for_sequelize_db:
  postgres_for_typeorm_db:
  postgres_for_mikroorm_db:
  mysql_for_prisma:
